app_name: user-service
image: ekasenya/user-app:v3.9

replicaCount: 2

service:
  type: NodePort
  port: 9099

postgresql:
  enabled: true
  postgresqlUsername: user
  postgresqlPassword: user
  postgresqlDatabase: user-db
  service:
      port: "5432"

job:
  restartPolicy: OnFailure

ingress:
  host:  arch.homework
  path: /user-service(/|$)(.*)
  port: 9099

metrics:
  serviceMonitor:
    enabled: true