{
 "title": "Nginx",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_nginx_process_cpu_seconds_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nginx_ingress_controller_nginx_process_resident_memory_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=~\"5.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_nginx_process_requests_total[1m])",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Latency 0.5 quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, ) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"user-ingress-helm\"}[1m]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 0.9 quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"user-ingress-helm\"}[1m]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 0.99 quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"user-ingress-helm\"}[1m]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency MAX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(1.0, sum by(le, ) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"user-ingress-helm\"}[1m]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}