{
 "title": "User service",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(path, method) (rate(app_request_count_total{http_status=~\"5.*\"}[1m]))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(path, method) (rate(app_request_count_total{path!~\"/|/metrics\"}[1m]))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Latency 50 quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, path, method) (rate(app_request_latency_seconds_bucket{path!~\"/|/metrics\"}[1m]))) * 1000",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Latency 95 quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, path, method) (rate(app_request_latency_seconds_bucket{path!~\"/|/metrics\"}[1m]))) * 1000",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Latency 99 quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, path, method) (rate(app_request_latency_seconds_bucket{path!~\"/|/metrics\"}[1m]))) * 1000",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Latency MAX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(1.0, sum by(le, path, method) (rate(app_request_latency_seconds_bucket{path!~\"/|/metrics\"}[1m]))) * 1000",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  }
 ]
}